import { ImageResponse } from "next/og";

export const alt = "Calap — Full-Stack Developer";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/**
 * Apple-minimal OG image — white, bold headline, blue dot accent.
 * Auto-generated by Next.js at /opengraph-image
 */
export default function OgImage(): ImageResponse {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          background: "#ffffff",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: "64px 80px",
          fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', Helvetica, Arial, sans-serif",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 32 }}>
          <div
            style={{
              width: 48,
              height: 48,
              borderRadius: 12,
              background: "#1d1d1f",
              color: "#fff",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              fontWeight: 700,
              fontSize: 24,
            }}
          >
            C
          </div>
          <span style={{ fontSize: 18, fontWeight: 600, color: "#86868b" }}>calap.dev</span>
          <span
            style={{
              marginLeft: 12,
              padding: "6px 12px",
              borderRadius: 9999,
              border: "1px solid #d2d2d7",
              fontSize: 13,
              color: "#86868b",
              display: "flex",
              alignItems: "center",
              gap: 6,
            }}
          >
            <span style={{ width: 6, height: 6, borderRadius: 9999, background: "#0071e3", display: "flex" }} />
            Available for freelance
          </span>
        </div>

        <div
          style={{
            fontSize: 72,
            fontWeight: 800,
            letterSpacing: "-0.04em",
            lineHeight: 0.95,
            color: "#1d1d1f",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <span style={{ display: "flex" }}>Crafting durable</span>
          <span style={{ display: "flex", color: "#0071e3" }}>systems for the web</span>
        </div>

        <div style={{ marginTop: 28, fontSize: 22, color: "#86868b", maxWidth: 720, lineHeight: 1.4, display: "flex" }}>
          Full-stack engineer — realtime infrastructure, state architectures, developer tooling.
        </div>
      </div>
    ),
    { ...size }
  );
}
